"""Added files table

Revision ID: 6feb4f2c5ba3
Revises: 
Create Date: 2022-09-29 20:53:10.410770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6feb4f2c5ba3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_title', sa.String(), nullable=True))
    op.add_column('files', sa.Column('output_keyword_float', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'output_keyword_float')
    op.drop_column('files', 'file_title')
    # ### end Alembic commands ###
